### PR TITLE
Added color-coded WP3 columns

### PR DESCRIPTION
**Pull request by kaiqu**
Sorry, this ended up both as an issue and a pull request - copying from the issue:

This is a new version of the spreadsheet with 2 new columns "WP3 - Attribute" and "WP3 - Entity" containing questions and mappings to the WP3 data model. The columns are color coded:
- Black = Matches the data model
- Blue = Tentative or naming difference
- Red = Questions and potential problems

I hope someone can make the time to check this and respond to the red and blue entries. The former are open questions, while the latter concern differences where I'm unsure whether the model automatically should conform (i.e. the dictionary contains the term "subject area", but I have been instructed to use "ISCED code" in the model).

### CODE REVIEW

**Comment by wrygiel** [comment]
Link to the related issue: https://github.com/erasmus-without-paper/ewp-wp2-data-dictionary/issues/2

BTW, initially, GitHub was supposed to be used for storing **code and API specifications only**. Stefan wanted to try putting this to GitHub, so we did. However, diffing Excel and PDF files requires knowledge of tools, which - I suspect - guys from @erasmus-without-paper/wp2 might not be familiar with. If this is true, then it might be easier to move WP2 documents out of GitHub (and propose changes by email). I think we should leave it up to WP2 members to decide where they want their documents stored.

**Comment by kaiqu** [comment]
> BTW, initially, GitHub was supposed to be used for storing code and API specifications only. Stefan wanted to try putting this to GitHub, so we did. However, diffing Excel and PDF files requires knowledge of tools, which - I suspect - guys from @erasmus-without-paper/wp2 might not be familiar with. If this is true, then it might be easier to move WP2 documents out of GitHub (and propose changes by email). I think we should leave it up to WP2 members to decide where they want their documents stored.

Sounds good - but in this case, diffing isn't necessary, since I have only added 2 columns with color-coded comments. (So it's not really a proposed version, but an alternative to raising an issue)

**Comment by wrygiel** [comment]
I believe this is a stale pull-request. I will close it. @kaiqu, please confirm when you're online.

**Comment by kaiqu** [comment]
> I believe this is a stale pull-request. I will close it. @kaiqu, please confirm when you're online.

I can confirm that this one is stale, yes.

**Pull request closed without merging**
